content/1-reactivity/1-declare-state/angular/name.component.ts
content/1-reactivity/2-update-state/angular/name.component.ts
content/1-reactivity/3-computed-state/angular/doublecount.component.ts

This is the angular implementation of the reactivity directory

adding angular implementation to 1-reactivity directory

---

content/4-component-composition/1-props/react/UserProfile.jsx
content/4-component-composition/1-props/svelte/UserProfile.svelte
content/4-component-composition/1-props/vue3/UserProfile.vue

Using `join` instead of `split` on array

fix props section

---

content/1-reactivity/1-declare-state/angular/name.component.ts
content/1-reactivity/2-update-state/angular/name.component.ts
content/1-reactivity/3-computed-state/angular/doublecount.component.ts
content/2-templating/4-event-click/angular/counter.component.ts
content/2-templating/6-conditional/angular/trafficlight.component.ts
content/3-lifecycle/1-on-mount/angular/pagetitle.component.html
content/3-lifecycle/1-on-mount/angular/pagetitle.component.ts
content/3-lifecycle/2-on-unmount/angular/time.component.html
content/3-lifecycle/2-on-unmount/angular/time.component.ts
content/4-component-composition/1-props/angular/app.component.html
content/4-component-composition/1-props/angular/app.component.ts
content/4-component-composition/1-props/angular/userprofile.component.html
content/4-component-composition/1-props/angular/userprofile.component.ts

This is a pull request for some adding and updating.

Updating and adding of angular components

---

content/4-component-composition/1-props/vue3/App.vue

match examples by Svelte, React & Angular

update prop passing for vue example

---

content/4-component-composition/2-emit-event/angular/answer-button.component.html
content/4-component-composition/2-emit-event/angular/answer-button.component.ts
content/4-component-composition/2-emit-event/angular/app.component.html
content/4-component-composition/2-emit-event/angular/app.component.ts
content/4-component-composition/3-slot/angular/app.component.ts
content/4-component-composition/3-slot/angular/funny-button.component.css
content/4-component-composition/3-slot/angular/funny-button.component.ts
content/6-form-input/1-input-text/angular/input-hello.component.ts
content/6-form-input/2-checkbox/angular/is-available.component.ts
content/6-form-input/3-radio/angular/pick-pill.component.ts
content/6-form-input/4-select/angular/color-select.component.ts
content/7-webapp-features/1-routing/angular/app.module.ts
content/7-webapp-features/2-router-link/angular/app.component.html
package.json
pnpm-lock.yaml

- component-composition
- emit-event
- slot
- form-input
- input-text
- checkbox
- radio
- select
- web-features
- routing
- router-link

add some angular examples

---

content/3-lifecycle/1-on-mount/angular/pagetitle.component.ts
content/3-lifecycle/1-on-mount/react/PageTitle.jsx
content/3-lifecycle/2-on-unmount/angular/time.component.ts
content/3-lifecycle/2-on-unmount/react/Time.jsx

If you don't provide an empty array in useEffect, it will run whenever component is updated, so it is basically almost same as not writing useEffect.

Update onMount of React

---

content/2-templating/4-event-click/react/Counter.jsx

In React, when updating a state that depends on its own current value, use an updater function
See https://reactjs.org/docs/hooks-reference.html#functional-updates

Update counter react

---

content/1-reactivity/3-computed-state/angular/doublecount.component.ts
content/2-templating/2-styling/angular/cssstyle.component.html
content/2-templating/5-dom-ref/angular/inputfocused.component.html
content/2-templating/5-dom-ref/angular/inputfocused.component.ts
content/3-lifecycle/1-on-mount/angular/pagetitle.component.html
content/3-lifecycle/1-on-mount/angular/pagetitle.component.ts
content/3-lifecycle/2-on-unmount/angular/time.component.html
content/3-lifecycle/2-on-unmount/angular/time.component.ts
content/4-component-composition/1-props/angular/app.component.html
content/4-component-composition/2-emit-event/angular/answer-button.component.html
content/4-component-composition/2-emit-event/angular/answer-button.component.ts
content/4-component-composition/4-slot-fallback/angular/app.component.html
content/4-component-composition/4-slot-fallback/angular/app.component.ts
content/4-component-composition/4-slot-fallback/angular/funny-button.component.css
content/4-component-composition/4-slot-fallback/angular/funny-button.component.ts
content/6-form-input/1-input-text/angular/input-hello.component.ts

Hey there !
I reached you out on Discord about some issues that I found on the Angular templates
I took the liberty to fix the other I noticed in the other Angular snippets, I also added a snippet for the `Slot Fallback` section.
My changes are:
- Formatting (one liners in `.html` has been moved to `template: '...'` 
- Improvements (removed unnecessary Angular code when there was some, like setting the component change strategy)
- Missing snippets (the `Slot Fallback` one)
Please feel free to tell me if you want me to update anything else on the changes I made !

Minor improvements on Angular snippets

---

content/4-component-composition/4-slot-fallback/angular/app.component.html
content/4-component-composition/4-slot-fallback/angular/funny-button.component.ts

Fix the slot fallback example for Angular introduced in #41 using [@nartc's suggestion](https://github.com/matschik/component-party/issues/29#issuecomment-1117343154)

Correct the slot fallback example

---

content/2-templating/6-conditional/vue3/TrafficLight.vue

`red/orange/green` switcher doesn't work correctly. Small fix for that.

Fix Vue conditional example

---

content/6-form-input/1-input-text/solid/InputHello.jsx

Add input-text example for solidjs

feat(form-input): add solid input-text

---

content/4-component-composition/2-emit-to-parent/react/App.jsx

Bonjour Mathieu, 
J'ai modifié pour React, le paramètre style dans la balise p du composant emit-to-parent, il me semble qu'elle était écrite à la manière de vue.js :)

fix react style in emit-to-parent component

---

README.md
content/7-webapp-features/1-fetch-data/vue3/App.vue
content/7-webapp-features/1-fetch-data/vue3/useFetchUsers.js

Hi, thanks for this great repo.
Just adding a fetch data example for vue3.
Let me know if there's anything you'd like me to change.

Add fetch data for vue3

---

content/7-webapp-features/1-fetch-data/ember/demo.hbs
content/7-webapp-features/1-fetch-data/ember/demo.js

Many many thanks to @MehulKChaudhari
in https://github.com/matschik/component-party/pull/80 for getting this started and sparking some good conversation! <3 :partying_face:

Add fetch example for ember

---

README.md
content/7-webapp-features/1-fetch-data/alpine/index.html
content/7-webapp-features/2-router-link/alpine/alpine.md
content/7-webapp-features/3-routing/alpine/alpine.md

Added examples to the fetch, router link, and routing examples for alpine. Let me know how these work!

[Feat] add-alpine-webapp-features

---

.gitignore
.vscode/extensions.json
.vscode/launch.json
.vscode/settings.json
README.md

Devops: improve the development environment and  vs-code settings

---

content/2-templating/2-styling/react/CssStyle.jsx

Fix: Incorrect React styling

---

content/4-component-composition/3-slot/qwik/App.tsx
content/4-component-composition/3-slot/qwik/FunnyButton.tsx
src/frameworks.mjs

Adds the "Slot" Qwik implementation featuring Funny Button.

feat(qwik): add funny button example

---

content/4-component-composition/2-emit-to-parent/qwik/AnswerButton.tsx
content/4-component-composition/2-emit-to-parent/qwik/App.tsx
src/frameworks.mjs

Adds the "Emit to parent" Qwik implementation featuring Answer Button.

feat(qwik): add answer button example

---

content/4-component-composition/1-props/qwik/App.tsx
content/4-component-composition/1-props/qwik/UserProfile.tsx
src/frameworks.mjs

Adds the "Props" Qwik implementation featuring User Profile.

feat(qwik): add user profile example

---

content/3-lifecycle/2-on-unmount/qwik/Time.tsx
src/frameworks.mjs

Adds the "On unmount" Qwik implementation featuring Time.

feat(qwik): add time example

---

content/2-templating/6-conditional/qwik/TrafficLight.tsx
src/frameworks.mjs

Adds the "Dom ref" Qwik implementation featuring Traffic Lights.

feat(qwik): add traffic light example

---

.prettierrc
README.md
content/1-reactivity/1-declare-state/vue2/Name.vue
content/1-reactivity/2-update-state/vue2/Name.vue
content/1-reactivity/3-computed-state/vue2/DoubleCount.vue
content/2-templating/1-minimal-template/vue2/HelloWorld.vue
content/2-templating/2-styling/vue2/CssStyle.vue
content/2-templating/3-loop/vue2/Colors.vue
content/2-templating/4-event-click/vue2/Counter.vue
content/2-templating/5-dom-ref/vue2/InputFocused.vue
content/2-templating/6-conditional/vue2/TrafficLight.vue
content/3-lifecycle/1-on-mount/vue2/PageTitle.vue
content/3-lifecycle/2-on-unmount/vue2/Time.vue
content/4-component-composition/1-props/vue2/App.vue
content/4-component-composition/1-props/vue2/UserProfile.vue
content/4-component-composition/2-emit-to-parent/vue2/AnswerButton.vue
content/4-component-composition/2-emit-to-parent/vue2/App.vue
content/4-component-composition/3-slot/vue2/App.vue
content/4-component-composition/3-slot/vue2/FunnyButton.vue
content/4-component-composition/4-slot-fallback/vue2/App.vue
content/4-component-composition/4-slot-fallback/vue2/FunnyButton.vue
content/6-form-input/1-input-text/vue2/InputHello.vue
content/6-form-input/2-checkbox/vue2/IsAvailable.vue
content/6-form-input/3-radio/vue2/PickPill.vue
content/6-form-input/4-select/vue2/ColorSelect.vue
content/7-webapp-features/1-fetch-data/vue2/App.vue
content/7-webapp-features/2-router-link/vue2/nuxt3.md
content/7-webapp-features/3-routing/vue2/nuxt3.md
src/frameworks.mjs

feat: add vue2

---

build/generateContentVitePlugin.js
package.json
pnpm-lock.yaml
src/components/FrameworkLabel.svelte

Resolves: #134 
- fix fs watcher support using Chokidar
- add support for fmw logos in dev environment

v2 fix dev env minor bugs

---

content/7-webapp-features/1-render-app/vue2/App.vue
content/7-webapp-features/1-render-app/vue2/index.html
content/7-webapp-features/1-render-app/vue2/main.js
content/7-webapp-features/1-render-app/vue3/App.vue
content/7-webapp-features/1-render-app/vue3/index.html
content/7-webapp-features/1-render-app/vue3/main.js

add Vue2 and Vue3 render app features

Feature:  Add Web App Features > Render Vue app

---

README.md
content/7-webapp-features/1-render-app/vue2/App.vue
content/7-webapp-features/1-render-app/vue2/index.html
content/7-webapp-features/1-render-app/vue2/main.js
content/7-webapp-features/1-render-app/vue3/App.vue
content/7-webapp-features/1-render-app/vue3/index.html
content/7-webapp-features/1-render-app/vue3/main.js

update readme about vue todo

---

README.md
content/7-webapp-features/1-render-app/solid/App.jsx
content/7-webapp-features/1-render-app/solid/index.html
content/7-webapp-features/1-render-app/solid/main.jsx
frameworks.mjs

feat(content): add render app > solid

---

README.md

A _component composition context_ example has already been added here: https://github.com/matschik/component-party/pull/160

Update Ember percentages README.md

---

content/2-templating/3-loop/svelte/Colors.svelte

E.g. react and vue also have keyed loops in their examples.

Add key to each block to align with other examples (Svelte, loop)

---

content/4-component-composition/2-emit-to-parent/svelte/AnswerButton.svelte
content/4-component-composition/2-emit-to-parent/svelte/App.svelte

You would usually not export callbacks, Svelte has its own way of dispatching custom events.
Also, the functions to set a flag are a waste of space and not required in Svelte either.

Svelte: More idiomatic "emit to parent"

---

content/4-component-composition/4-slot-fallback/lit/funny-button.js

prefer using performant static css tag over runtime styleMap()

Prefer `css` over `styleMap()`

---

content/7-webapp-features/1-render-app/angular/app-routing.module.ts
content/7-webapp-features/1-render-app/angular/app.component.ts
content/7-webapp-features/1-render-app/angular/app.module.ts
content/7-webapp-features/1-render-app/angular/index.html

Noticed the example for Angular was missing under WebApp features / App render.

Added WebApp Features / App Render snippet for Angular

---

content/2-templating/6-conditional/alpine/index.html
content/2-templating/6-conditional/angular/trafficlight.component.ts
content/2-templating/6-conditional/aurelia1/traffic-light.ts
content/2-templating/6-conditional/aurelia2/traffic-light.ts
content/2-templating/6-conditional/ember/traffic-light.js
content/2-templating/6-conditional/lit/traffic-light.js
content/2-templating/6-conditional/mithril/TrafficLight.js
content/2-templating/6-conditional/qwik/TrafficLight.tsx
content/2-templating/6-conditional/react/TrafficLight.jsx
content/2-templating/6-conditional/solid/TrafficLight.jsx
content/2-templating/6-conditional/svelte/TrafficLight.svelte
content/2-templating/6-conditional/vue2/TrafficLight.vue
content/2-templating/6-conditional/vue3/TrafficLight.vue

This bit of code is the same in all of the examples, rather long so it takes up space, and not relevant at all to the frameworks themselves.
I don't know all of these frameworks so I may have made some errors in the translation.

Simplify next traffic light functions.

---

content/4-component-composition/5-context/svelte5/UserProfile.svelte
content/4-component-composition/5-context/svelte5/createUserState.js

This would probably be the better way to write this with Svelte 5. My initial implementation was probably a bit too direct of a translation from Svelte 4

feat(svelte): demonstrate fine-grained reactivity

---

content/4-component-composition/5-context/svelte5/App.svelte
content/4-component-composition/5-context/svelte5/UserProfile.svelte

Added a fix in component composition example for svelte5 where user state is incorrectly accessed.

fix: fixed incorrect accessors when using userState

---

content/2-templating/6-conditional/angular/trafficlight.component.ts

Updated traffic light example for newest production version of Angular.

Update trafficlight.component.ts for Angular 17

---

content/3-lifecycle/1-on-mount/svelte5/PageTitle.svelte

fix pageTitle not being shown/udpated

fix: add rune $state to PageTitle.svelte

---

content/2-templating/5-dom-ref/vue3/InputFocused.vue

https://vuejs.org/api/composition-api-helpers.html#usetemplateref

Update dom-ref example for Vue 3

---

content/3-lifecycle/2-on-unmount/qwik/Time.tsx

Ref. [Qwik cleanup tasks](https://qwik.dev/docs/components/tasks/#cleanup)

fix(qwik): use cleanup function to unmount

---

content/2-templating/1-minimal-template/qwik/HelloWorld.tsx

Ref. [Qwik Inline Components](https://qwik.dev/docs/components/overview/#inline-components)

feat(qwik): use the inline component syntax for the minimal template example

---

content/3-lifecycle/2-on-unmount/vue2/Time.vue
content/4-component-composition/1-props/vue2/UserProfile.vue

https://v2.vuejs.org/v2/api/#beforeDestroy

fix: On unmount  example for Vue2

---

content/7-webapp-features/2-fetch-data/lit/fetch-users-task.js
content/7-webapp-features/2-fetch-data/lit/x-app.js

in Lit fetch data use case move function to another file 

---

content/1-reactivity/1-declare-state/angularRenaissance/name.component.ts
content/1-reactivity/2-update-state/angularRenaissance/name.component.ts
content/1-reactivity/3-computed-state/angularRenaissance/doublecount.component.ts
content/2-templating/1-minimal-template/angularRenaissance/helloworld.component.ts
content/2-templating/2-styling/angularRenaissance/cssstyle.component.ts
content/2-templating/3-loop/angularRenaissance/colors.component.ts
content/2-templating/4-event-click/angularRenaissance/counter.component.ts
content/2-templating/5-dom-ref/angularRenaissance/inputfocused.component.ts
content/2-templating/6-conditional/angularRenaissance/trafficlight.component.ts
content/3-lifecycle/1-on-mount/angularRenaissance/pagetitle.component.ts
content/3-lifecycle/2-on-unmount/angularRenaissance/time.component.ts
content/4-component-composition/1-props/angularRenaissance/app.component.ts
content/4-component-composition/1-props/angularRenaissance/userprofile.component.ts
content/4-component-composition/2-emit-to-parent/angularRenaissance/answer-button.component.ts
content/4-component-composition/2-emit-to-parent/angularRenaissance/app.component.ts
content/4-component-composition/3-slot/angularRenaissance/app.component.ts
content/4-component-composition/3-slot/angularRenaissance/funny-button.component.ts
content/4-component-composition/4-slot-fallback/angularRenaissance/app.component.ts
content/4-component-composition/4-slot-fallback/angularRenaissance/funny-button.component.ts
content/4-component-composition/5-context/angularRenaissance/app.component.ts
content/4-component-composition/5-context/angularRenaissance/user-profile.component.ts
content/6-form-input/1-input-text/angularRenaissance/input-hello.component.ts
content/6-form-input/2-checkbox/angularRenaissance/is-available.component.ts
content/6-form-input/3-radio/angularRenaissance/pick-pill.component.ts
content/6-form-input/4-select/angularRenaissance/color-select.component.ts
content/7-webapp-features/1-render-app/angularRenaissance/app.component.ts
content/7-webapp-features/2-fetch-data/angularRenaissance/users.component.ts
package.json
pnpm-lock.yaml

Angular 19 makes component standalone by default, no need to contain `standalone: true`

Upgrade Angular Renaissance to Angular 19(Remove standalone flag)

---

content/2-templating/4-event-click/ripple/Counter.ripple
content/3-lifecycle/1-on-mount/ripple/PageTitle.ripple
content/3-lifecycle/2-on-unmount/ripple/Time.ripple

there were still 3 code examples that were using the old $ reactivity system

fix(ripple): use new reactivity system
