- content/1-reactivity/3-computed-state/vue3/DoubleCount.vue
- The Vue3 snippet show an  unnecessary `<template>` "section" which make the snippet look more verbose than it should.
- Removing this section make a fairer comparison
```
<template>
<div/>
</template>
```
> Remove unnecessary <template> element in vue3 computed snippet

- content/3-lifecycle/2-on-unmount/react/Time.jsx
The interval was created at each render, creating a memory leak
> Fix react time example

- content/2-templating/6-conditional/react/TrafficLight.jsx
It's more a question of taste, but I think it makes the example more concise
> Proposal : Remove unnecessary useMemo in TrafficLight react example

- content/2-templating/5-dom-ref/react/InputFocused.jsx
In React, to run a useEffect on mount, we pass an empty array, otherwise it would be run on each render
> Update InputFocused React

- content/1-reactivity/1-declare-state/lit/index.html
- content/1-reactivity/1-declare-state/lit/name.js
This PR addresses a two things:
1. Other examples showcase _reactive_ state (`useState` in React, for example). The current example was not using reactive state. Using the `@state()` decorator makes this class field reactive (As internal state). `@property()` would also be valid but I think that's better for the `Component composition` section
2. Custom elements _must_ have a dash (`-`) in their name, so I changed it to `x-name` (`x` being a generic prefix that could be replaced by anything).
3. Custom elements cannot be self-closing AFAIK.
> fix(lit): use reactive state on declare-state example

- content/4-component-composition/3-slot/solid/FunnyButton.jsx
- content/4-component-composition/4-slot-fallback/solid/FunnyButton.jsx
In Solid, the `children` helper isn't required to place `props.children` in JSX. The slot examples in the content section could be written similarly to React. Minus the destructuring of course.
[some proof](https://playground.solidjs.com/?hash=432759760&version=1.4.1)
The purpose of `children` helper is to resolve all of the nested arrays/functions inside `props.children` to a flat array. This is so that they are easier to map, for example for [animating html elements](https://github.com/solidjs/solid-transition-group/blob/22739eddb2087597e183f0e47d3d3109c4af0c95/src/TransitionGroup.ts#L59).
> Correct Solid slot examples

- content/2-templating/6-conditional/svelte/TrafficLight.svelte
The conditional templating example, all frameworks except Svelte have `<span>` tags wrapping the conditional templates.
For the sake of consistency when comparing syntaxes I think it is better to add spans to Svelte too.
I'm sure all of the other frameworks also have the ability to conditionally swap between plain text. Although probably with varying syntaxes. Maybe worth a separate example?
> add spans to svelte conditional templating

- content/7-webapp-features/1-routing/solid/solid-app-router.md
- content/7-webapp-features/2-router-link/solid/solid-app-router.md
Once more with an example for Solid. Using `solid-app-router`! Its syntax is similar to react-router-dom.
> feat(solid): add router example

- content/7-webapp-features/1-routing/lit/vaadin.md
- content/7-webapp-features/2-router-link/lit/vaadin.md
Me again!
Felt it looked a bit incomplete without a routing example so, even if it's not an "official" solution, I added an example with `@vaadin/router` which is a quite popular solution (and the most "kitchen sink" kind of solution I've found). I personally have used this library as well. The example itself I took out of the `Getting started` from its docs.
Other alternatives I've seen are either handling it as a multi-page app (multiple HTML files with the built-in browser navigation), or manually hooking into the `popstate` event to handle navigation events yourself. But this one is concise enough for a snippet, I feel.
> feat(lit): add router example

- content/7-webapp-features/1-fetch-data/angular/user.d.ts
- content/7-webapp-features/1-fetch-data/angular/user.service.ts
- content/7-webapp-features/1-fetch-data/angular/users.component.html
- content/7-webapp-features/1-fetch-data/angular/users.component.ts
- content/7-webapp-features/1-fetch-data/angular/users.module.ts
In angular, fetching data is done with `HttpClient`, which exposes the result as a RxJS Observable containing the data (which is automatically mapped to an array of users in the get method of the HttpClient using the User interface declared in `user.d.ts` ). HttpClientModule has to be imported in the module where the component is declared on and the service is set to be a provider of.
```
import { UsersComponent } from './users.component';
@NgModule({
declarations: [
UsersComponent
],
imports: [
BrowserModule,
HttpClientModule
],
providers: [UserService],
```
It's also a good and common practice to fetch the data on a service so it's accessible from anywhere and there's no redundant observables and data.
I've handled the data fetch and loadingOrError with the async pipe in the template …
> feat(angular): add data fetch example

- content/1-reactivity/3-computed-state/react/DoubleCount.jsx
It's not idiomatic to use useMemo for such a cheap calculation.
https://canimerge.com/should-you-really-use-usememo-in-react-lets-find-out/
https://blog.logrocket.com/rethinking-hooks-memoization/
> Remove useMemo for simple calculation

- .vscode/extensions.json
The `johnsoncodehk.volar` extension from the list of workspace recommendations have the issue:  not found in marketplace.
Change the recommended extension entry  from `johnsoncodehk.volar` to `vue.volar`.
> fix(development-environment): remove "johnsoncodehk.volar" entry from recommended extensions list

- content/7-webapp-features/3-routing/svelte/sveltekit.md
Updates the SvelteKit routing section to reflect new changes in the framework in version 1.0.0-next.406.
> fix(svelte): update sveltekit routing fs example

- content/2-templating/5-dom-ref/qwik/InputFocused.tsx
- src/frameworks.mjs
Adds the "Dom ref" Qwik implementation featuring Input Focus.
> feat(qwik): add input focused example

- content/3-lifecycle/1-on-mount/qwik/PageTitle.tsx
- src/frameworks.mjs
Adds the "On mount" Qwik implementation featuring Page Title.
> feat(qwik): add page title example

- README.md
- content/4-component-composition/4-slot-fallback/qwik/App.tsx
- content/4-component-composition/4-slot-fallback/qwik/FunnyButton.tsx
- content/6-form-input/1-input-text/qwik/InputHello.tsx
- content/6-form-input/2-checkbox/qwik/IsAvailable.tsx
- content/6-form-input/3-radio/qwik/PickPill.tsx
- content/6-form-input/4-select/qwik/ColorSelect.tsx
- content/7-webapp-features/1-fetch-data/qwik/App.tsx
- content/7-webapp-features/1-fetch-data/solid/App.jsx
- content/7-webapp-features/2-router-link/qwik/qwik-city.md
- content/7-webapp-features/3-routing/qwik/qwik-city.md
- package.json
- pnpm-lock.yaml
Adding missing examples for Qwik.
There's a slight caveat with fallback content. [It's not working currently with the instructions described on the documentation](https://qwik.builder.io/docs/components/projection/#default-slot-content), this seems to be [intentional with no immediate plans to bring the feature back](https://github.com/BuilderIO/qwik/issues/1106). I made the example using some of the recommendations from the thread (and Discord). Added this as a comment on the example itself.
> feat(qwik): add missing examples

- content/1-reactivity/1-declare-state/angular/name.component.ts
- content/1-reactivity/2-update-state/angular/name.component.ts
- content/1-reactivity/3-computed-state/angular/doublecount.component.ts
- content/2-templating/1-minimal-template/angular/helloworld.component.ts
- content/3-lifecycle/1-on-mount/angular/pagetitle.component.ts
- content/3-lifecycle/2-on-unmount/angular/time.component.ts
- content/4-component-composition/3-slot/angular/app.component.ts
- content/6-form-input/1-input-text/angular/input-hello.component.ts
- content/7-webapp-features/3-routing/angular/app.module.ts
- src/components/CodeHighlight/highlightAngularComponent.js
- src/components/FileCode.astro
This PR resolves this issue: [Code highlight for Angular inline template and styles](https://github.com/matschik/component-party/issues/100)
Example:
Before: 
After: 
NOTE: 
I had to convert all Angular templates to use `` (backticks) in order to grab them easily with regex and do the replacements.
> Added syntax highlighting for angular component templates

- content/1-reactivity/3-computed-state/lit/double-count.js
If you don't need state to be accessed publicly or in multiple methods, you can just use statements in the render() method.
> Update Lit's computed state snippet to not create a public field.

- README.md
- content/4-component-composition/5-context/vue3/App.vue
- content/4-component-composition/5-context/vue3/UserProfile.vue
The context sample for vue3 was missing. Here you have one using the the Provide / Inject mechanism:
https://vuejs.org/guide/components/provide-inject.html#provide-inject
> content: add context sample for vue3

- README.md
- content/4-component-composition/5-context/vue2/App.vue
- content/4-component-composition/5-context/vue2/UserProfile.vue
The context sample for vue2 was missing.
> Add Component composition > Context for vue2

- README.md
- content/4-component-composition/5-context/qwik/App.tsx
- content/4-component-composition/5-context/qwik/UserProfile.tsx
The render app and context sample for qwik was missing.
> Add Component composition > Context for Qwik

- content/4-component-composition/5-context/ember/app.hbs
- content/4-component-composition/5-context/ember/user-profile.hbs
- content/4-component-composition/5-context/ember/user-profile.js
- content/4-component-composition/5-context/ember/user-service.js
Ember doesn't have contexts exactly, but services can serve as a similar alternative.
> Ember "Context" Example

- content/4-component-composition/2-emit-to-parent/svelte/AnswerButton.svelte
- content/4-component-composition/2-emit-to-parent/svelte/App.svelte
Add more readable version of passing functions to children:
```html
<script>
export let onYes;
export let onNo;
</script>
<button on:click={onYes}> YES </button>
<button on:click={onNo}> NO </button>
```
> refactor: :recycle: Add simpler way of passing functions to children in svelte

- content/1-reactivity/2-update-state/react/Name.jsx
Setting state in the body of the component will cause below error:
> Error
Too many re-renders. React limits the number of renders to prevent an infinite loop.
So to change name for once, it has to be run inside of useEffect:
```jsx
import { useEffect, useState } from "react";
export default function App() {
const [name, setName] = useState("John");
useEffect(()=>setName("Jane"),[])
return <h1>Hello {name}</h1>;
}
```
> fix: :bug: fix react infinite loop error

- content/2-templating/5-dom-ref/lit/input-focused.js
Lit team prefers suggesting `@query` over `ref`. Though this example is simple enough to just do `this.renderRoot.querySelector('input')!.focus()` as well, the title for this section is "dom-ref"
> Prefer `@query` over `ref()`

- content/2-templating/2-styling/vue2/CssStyle.vue
- content/2-templating/2-styling/vue3/CssStyle.vue
- content/2-templating/4-event-click/vue2/Counter.vue
- content/2-templating/4-event-click/vue3/Counter.vue
- content/2-templating/6-conditional/vue2/TrafficLight.vue
- content/2-templating/6-conditional/vue3/TrafficLight.vue
- content/4-component-composition/2-emit-to-parent/vue2/AnswerButton.vue
- content/4-component-composition/2-emit-to-parent/vue3/AnswerButton.vue
- content/7-webapp-features/2-fetch-data/vue2/App.vue
- content/7-webapp-features/2-fetch-data/vue3/App.vue
- frameworks.mjs
This makes the code more comparable to Svelte, React, Alpine, etc.
Note: this PR is a follow-up to #187. This time I changed the linter to be consistent with the changes (by setting a custom value for the [vue/singleline-html-element-content-newline](https://eslint.vuejs.org/rules/singleline-html-element-content-newline.html) eslint rule). I believe this change aligns with the spirit of the project, which is to make the various sample code blocks comparable to each other.
Some examples:
| Before | After |
| ------ | ----- |
| ![image](https://github.com/matschik/component-party.dev/assets/478237/a2b278ca-44e6-43b9-b790-b9c5c9d5f814) | ![image](https://github.com/matschik/component-party.dev/assets/478237/3d04d421-e11d-4b1c-9194-2392b015976f) |
| …
> Change Vue 2 and Vue 3 examples to compact mode

- content/2-templating/4-event-click/svelte5/Counter.svelte
- content/4-component-composition/2-emit-to-parent/svelte5/AnswerButton.svelte
- content/4-component-composition/2-emit-to-parent/svelte5/App.svelte
- content/4-component-composition/3-slot/svelte5/FunnyButton.svelte
- content/4-component-composition/4-slot-fallback/svelte5/FunnyButton.svelte
- content/7-webapp-features/1-render-app/svelte5/app.js
This PR updates some of the Svelte 5 examples to reflect some changes made since the original Svelte 5 announcements:
- [Components are now functions instead of classes](https://svelte-5-preview.vercel.app/docs/breaking-changes#components-are-no-longer-classes), and so require the new `mount` function to be rendered.
- The `on:` directive and `createEventDispatcher` are now deprecated in favor of using regular callback props (similarly to React)
- Slots are deprecated in favor of snippets: a new way to create reusable markup and pass it down to components.
Please let me know if I missed anything or if something needs to be updated to better fit Svelte 5's intended use!
Closes #201
> Update Svelte 5 examples

- content/6-form-input/1-input-text/angular/input-hello.component.ts
- content/6-form-input/2-checkbox/angular/is-available.component.ts
- content/6-form-input/3-radio/angular/pick-pill.component.ts
- content/6-form-input/4-select/angular/color-select.component.ts
Angular introduced [Standalone Component](https://angular.io/guide/standalone-components) since v14(as developer preview feature). It became stable in v15 and now in v17, is enabled by default when generating components using cli. Since it eliminates the need for ngModule, it is easier to manage imports for individual components like the examples here. I am able to show the use of built-in modules without adding a new ngModule file to the example.  
Angular's built-in templated driven [FormsModule](https://angular.io/guide/forms-overview#setup-in-template-driven-forms) allows two-way binding, which makes more sense and is easier to implement for simple input examples.
> Convert Angular input examples into standalone component & switch to two-way binding

- src/App.svelte
As reported by @khang-nd, the framework navbar does not allow scrolling on larger zoom screens or smaller screens.
To fix that, I removed the class `no-scroll` from the navbar; allowing the user to better navigate when choosing frameworks.
> Fix framework navbar scroll

- content/4-component-composition/3-slot/angular/funny-button.component.ts
- content/4-component-composition/4-slot-fallback/angular/funny-button.component.ts
Some Angular components don't have correct selector, renaming them to match the ones used in parent components.
> Fix incorrect Angular component selectors

- content/3-lifecycle/1-on-mount/svelte5/PageTitle.svelte
`$effect()` runs after the component gets mounted and rendered, but `pageTitle` isn't reactive. Thus, the page won't re-render with the new value. For this logic, it's better to use `$effert.pre()` - it runs before mounting and the first rendering. But as the example concerns the on-mount event, it makes more sense to make `pageTitle` reactive.
You can try both solutions on [the Svelte 5 playground](https://svelte-5-preview.vercel.app/#H4sIAAAAAAAAA1WOwQqDMAyGXyWEHRTGvDtX2BvssNvcQWocgVqLjY5Rffe1Gwiewv-R_0sCdmzIY_kIaJuesMSrc3hE-bgU_ExGKGY_TKNOpPJ6ZCeqtgCGBFzzojuLIbhAjWxZGgNzYyaq8ZyWDtR1pCXLcrgoCAnBrtUOeurJykl-YFmix9J7J1nzOKpiux2DU7cogX-JfQlhk65V4VR8uh9a7phaLGWcaH2uXwXAXF7vAAAA).
> fix Svelte 5 on-mount

- content/3-lifecycle/1-on-mount/svelte4/PageTitle.svelte
- content/3-lifecycle/1-on-mount/svelte5/PageTitle.svelte
The other frameworks such as React do not include "is".
> fix(content): update PageTitle.svelte to match other frameworks

- src/components/Header.svelte
I noticed that when any framework is selected the "Share" button appears. Since that button has a padding of `py-1.5` and the GitHub button has a padding of `py-1`, it is slightly larger than the GitHub button which is causing the Header/nav to expand in height by a few pixels; causing a layout shift:
https://github.com/matschik/component-party.dev/assets/47110839/bd90843a-a130-46e0-9d4e-a1116ddce281
Just changing the share button's padding to `py-1` fixes the shifting, however, in my opinion it looks a bit off next to the GitHub button:
Because as you can see, the share button is slightly smaller than the GitHub button since it doesn't have a border:
So I've changed the styling to include a border and also match the framework buttons, hopefully that's ok:
As you can see, the shifting is …
> fix: content shifting when the copy button appears

- src/components/GithubStarButton.svelte
- src/components/Header.svelte
Same issue as #235, but on mobile and slightly different:
https://github.com/matschik/component-party.dev/assets/47110839/981fd534-3cb6-4287-ba32-cb656c050acb
The problem is that the title gets wrapped because of the share button being added and the GitHub button taking a lot of space.
An easy fix is to just hide the text and numbers on small screens, however, that will cause the GitHub button to look off next to the share button:
To fix this, I set the horizontal padding and the size of the icon to the same values as the share button:
As you can see, the shifting is gone after these changes:
https://github.com/matschik/component-party.dev/assets/47110839/f86919e4-6e14-4357-bf31-b55368b27161
> fix: content shifting when the copy button appears on mobile

- content/1-reactivity/1-declare-state/qwik/Name.tsx
- content/1-reactivity/2-update-state/qwik/Name.tsx
- content/1-reactivity/3-computed-state/qwik/DoubleCount.tsx
- content/2-templating/4-event-click/qwik/Counter.tsx
- content/2-templating/6-conditional/qwik/TrafficLight.tsx
- content/6-form-input/1-input-text/qwik/InputHello.tsx
- content/6-form-input/2-checkbox/qwik/IsAvailable.tsx
- content/6-form-input/3-radio/qwik/PickPill.tsx
- content/6-form-input/4-select/qwik/ColorSelect.tsx
I've come across this website (this whole thing is a great idea btw) and while looking at the examples for Qwik I found some of them has issues that either cause errors, or they just overcomplicated. This PR fixes and improves upon these examples. Namely:
1. Declare state: This fix is rather a simplification to be more comparable with the competitors (compared React, Vue, Svelte 5 and Qwik);
2. Update state: This example results in error, because the state must be updated within [`useTask$`](https://qwik.dev/docs/components/tasks/#usetask) callback when updated on initial render. In this example it will behave like an "on mount" lifecycle hook from other frameworks;
3. Computed state: This example is just misleading, because Qwik also has …
> Fixes and improvements for some of Qwik examples

- content/4-component-composition/1-props/vue2/UserProfile.vue
https://v2.vuejs.org/v2/guide/components.html#Passing-Data-to-Child-Components-with-Props
> fix: props example for Vue2

- src/Index.svelte
now that Svelte 5 is out, it probably makes sense to use it instead
> chore: default to svelte 5 instead of svelte 4

- vite.config.js
This PR:
- Moves Svelte 4 vs Svelte 5 from Current vs Upcoming to Legacy vs Current now that Svelte 5 is released.
- Removes Angular vs Angular Renaissance from Current vs Upcoming since it is already in Legacy vs Current.
> move Svelte 4 vs Svelte 5 and Angular vs Angular Renaissance in comparison footer

- build/lib/playgroundUrlByFramework.js
- content/1-reactivity/1-declare-state/marko/Name.marko
- content/1-reactivity/2-update-state/marko/Name.marko
- content/1-reactivity/3-computed-state/marko/DoubleCount.marko
- content/2-templating/2-styling/marko/CssStyle.marko
- content/2-templating/4-event-click/marko/Counter.marko
- content/2-templating/5-dom-ref/marko/InputFocused.marko
- content/2-templating/6-conditional/marko/TrafficLight.marko
- content/3-lifecycle/1-on-mount/marko/PageTitle.marko
- content/3-lifecycle/2-on-unmount/marko/Time.marko
- content/4-component-composition/1-props/marko/UserProfile.marko
- content/4-component-composition/2-emit-to-parent/marko/App.marko
- content/4-component-composition/3-slot/marko/FunnyButton.marko
- content/4-component-composition/4-slot-fallback/marko/FunnyButton.marko
- content/4-component-composition/5-context/marko/App.marko
- content/4-component-composition/5-context/marko/UserProfile.marko
- content/6-form-input/1-input-text/marko/InputHello.marko
- content/6-form-input/2-checkbox/marko/IsAvailable.marko
- content/6-form-input/3-radio/marko/PickPill.marko
- content/6-form-input/4-select/marko/ColorSelect.marko
- content/7-webapp-features/1-render-app/marko/app.js
- content/7-webapp-features/1-render-app/marko/index.html
- content/7-webapp-features/1-render-app/marko/index.marko
- content/7-webapp-features/2-fetch-data/marko/App.marko
- frameworks.mjs
**Marko 6 is out!** We have a new website, and APIs have been finalized. To celebrate, we're going through and updating Marko examples everywhere to use best practices and modern syntax.
This PR updates Marko examples, and switches the link generation so it works with our new playground.
> feat(marko): update examples for v6
